import React from "react";
import Head from "next/head";
import { ReactNode } from 'react';

import '../styles/globals.css'
import 'bootstrap/dist/css/bootstrap.min.css';
import type { AppProps } from 'next/app'

function MyApp({ Component, pageProps }: AppProps) {
  const getLayout = Component.getLayout ?? ((page: ReactNode) => page)
  return  <>
    <Head>
      <title>Wallet</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="./favicon.ico" />
    </Head>
    {getLayout(<Component {...pageProps} />)}
  </>
}

export default MyApp
